[package]
name = "rust"
version = "0.1.0"
authors = ["Martin Schröder <mkschreder.uk@gmail.com>"]
edition = "2018"

[lib]
name = "rust"
crate-type = ["staticlib"]

[dependencies]

[dependencies.cortex-m-rt]
version = "0.5.0"
